---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: dev
      annotations:
        tsb.tetrate.io/organization: tetrate
      labels:
        domain: dev
    spec:
      description: dev
      displayName: dev
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: bookinfo-dev-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        owner: bookinfo-dev-ws-team
      labels:
        app: bookinfo-dev
    spec:
      isolationBoundary: dev
      namespaceSelector:
        names:
          - "*/bookinfo-dev"
          - "*/tier1-dev"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-dev-gg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-dev-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo-dev"
          - "*/tier1-dev"
      configMode: BRIDGED
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-dev-tg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-dev-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo-dev"
          - "*/tier1-dev"
      configMode: BRIDGED
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-dev-sg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-dev-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo-dev"
          - "*/tier1-dev"
      configMode: BRIDGED
  - apiVersion: install.tetrate.io/v1alpha1
    kind: IngressGateway
    metadata:
      name: bookinfo-dev-gw
      namespace: bookinfo-dev
    spec:
      revision: dev-stable 
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: IngressGateway
    metadata:
      name: bookinfo-dev-igw
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-dev-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-dev-gg
    spec:
      workloadSelector:
        namespace: bookinfo-dev
        labels:
          app: bookinfo-dev-gw
      http:
        - name: productpage
          port: 80
          hostname: "bookinfo-dev.tetrate.io"
          routing:
            rules:
              - route:
                  host: "bookinfo-dev/productpage.bookinfo-dev.svc.cluster.local"
                  port: 9080
        - name: details
          port: 80
          hostname: "details.tetrate.io"
          routing:
            rules:
              - route:
                  host: "bookinfo-dev/details.bookinfo-dev.svc.cluster.local"
                  port: 9080
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: trafficgenerator
      name: trafficgenerator
      namespace: bookinfo-dev
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      selector:
        matchLabels:
          app: trafficgenerator
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: trafficgenerator
        spec:
          containers:
            - args:
                - /bin/sh
                - -c
                - 'while true; do curl -i -H"Host: bookinfo-dev.tetrate.io" bookinfo-dev-gw.bookinfo-dev/productpage; done'
              image: appropriate/curl
              imagePullPolicy: Always
              name: trafficgenerator
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
