{
 "title": "GitOps Operational Status",
 "description": "Operational metrics to indicate Cluster GitOps health",
 "tags": [
  "tsb",
  "gitops"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "gitopsInterval", "label": "Time period between updates", "query": "1m,5m,10m,30m,1h,6h,12h,1d,7d" }
  ]
 },
 "panels": [
  {
   "title": "GitOps Status",
   "type": "table",
   "description": "Shows the status of the GitOps component for each cluster.",
   "gridPos": { "h": 5, "w": 23, "x": 0, "y": 0 },
   "targets": [
    { "expr": "gitops_enabled" }
   ]
  },
  {
   "title": "Accepted Admission Requests",
   "type": "graph",
   "description": "Accepted admission requests for each cluster. This is the rate at which operations are processed by the GitOps relay and sent to TSB.",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitops_admission_count_total{allowed=\"true\"}[$gitopsInterval])) by (cluster_name, component)",
     "legendFormat": "{{cluster_name}} {{component}}"
    }
   ]
  },
  {
   "title": "Rejected Admission Requests",
   "type": "graph",
   "description": "Rejected admission requests for each cluster. This is the rate at which operations are processed by the GitOps relay and sent to TSB.\n\nA spike in these metrics may indicate an increase in invalid TSB resources being applied to the Kubernetes clusters, or error in the admission webhook processing.",
   "gridPos": { "h": 8, "w": 7, "x": 7, "y": 5 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitops_admission_count_total{allowed=\"false\"}[$gitopsInterval])) by (cluster_name, component)",
     "legendFormat": "{{cluster_name}} {{component}}"
    }
   ]
  },
  {
   "title": "Admission Review Latency",
   "type": "graph",
   "description": "Admission review latency percentiles grouped by cluster.\n\nThe GitOps admission reviews make decisions by forwarding the objects to the Management Plane. This metric helps understand the time it takes to make such decisions.\n\nA spike here may indicate network issues or connectivity issues between the Control Plane and the Management Plane.",
   "gridPos": { "h": 8, "w": 9, "x": 14, "y": 5 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(gitops_admission_duration_bucket{}[$gitopsInterval])) by (cluster_name, component, le))",
     "legendFormat": "{{cluster_name}} {{component}} P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(gitops_admission_duration_bucket{}[$gitopsInterval])) by (cluster_name, component, le))",
     "legendFormat": "{{cluster_name}} {{component}}  P95"
    }
   ]
  },
  {
   "title": "Resources Pushed to TSB",
   "type": "graph",
   "description": "Number of resources pushed to the Management Plane.\n\nThis should be equivalent to the admission requests in most cases, but this will also account for object pushes that are done by the background reconcile processes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitops_push_count_total{success=\"true\"}[$gitopsInterval])) by (cluster_name, component)",
     "legendFormat": "{{cluster_name}} {{component}}"
    }
   ]
  },
  {
   "title": "Failed pushes to TSB",
   "type": "graph",
   "description": "Number of resource pushes to the Management Plane that failed.\n\nThis should be equivalent to the failed admission requests in most cases, but this will also account for object pushes that are done by the background reconciliation processes.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitops_push_count_total{code!=\"OK\"}[$gitopsInterval])) by (cluster_name, component, code)",
     "legendFormat": "cluster={{cluster_name}} component={{component}} gRPC Code={{code}}"
    }
   ]
  },
  {
   "title": "Resources Conversions",
   "type": "graph",
   "description": "Number of Kubernetes resources that have been read from the cluster and successfully converted into TSB objects to be pushed to the Management plane.\n\nThe values for this metric should be the same as the Pushed Objects. If there is a difference between them, it probably means some issue when converting the Kubernetes objects to TSB objects.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitops_convert_count_total{success=\"true\"}[$gitopsInterval])) by (cluster_name, component)",
     "legendFormat": "{{cluster_name}} {{component}}"
    }
   ]
  },
  {
   "title": "Resources conversions errors",
   "type": "graph",
   "description": "Number of Kubernetes resources that have been read from the cluster and failed to be converted into TSB objects.\n\nA spike on this metric indicates that the Kubernetes objects could not be converted to TSB objects and that those resources were not sent to the Management Plane.",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(gitops_convert_count_total{success=\"false\"}[$gitopsInterval])) by (cluster_name, component)",
     "legendFormat": "{{cluster_name}} {{component}}"
    }
   ]
  }
 ]
}