{
 "title": "MPC Operational Status",
 "description": "Operational metrics to indicate Management Plane Controller (MPC) health.",
 "tags": [
  "tsb",
  "mpc"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "mpcTimePeriod", "label": "Time period between updates", "query": "1m,5m,10m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Config generation (TSB -> MPC -> XCP)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Get All Config Objects duration",
   "type": "timeseries",
   "description": "How long does it take to execute the GetAllConfigObjects grpc method to retrieve all the configuration objects.\nIf you want to know the error cause take a look at the grpc charts that contain the status response codes.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(max_over_time(mpc_get_all_config_objects_time{error=\"\", component=\"mpc\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "ok"
    },
    {
     "expr": "sum(max_over_time(mpc_get_all_config_objects_time{error=\"true\", component=\"mpc\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Received configs",
   "type": "timeseries",
   "description": "The number of resources that sent from TSB to MPC.\n\nThis metric shows the number of objects that are created, updated, and deleted as part of a configuration push from MPC to XCP.\n\nThis metric can be used together with the XCP push operations and push duration to get an understanding of how the amount of resources being pushed to XCP affects the time it takes for the entire configuration push operation to complete.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(max_over_time(mpc_tsb_config_received_count{resource=\"\", component=\"mpc\"}[$mpcTimePeriod])) by(component)",
     "legendFormat": "Received from TSB"
    }
   ]
  },
  {
   "title": "Config Processing duration",
   "type": "timeseries",
   "description": "Time it takes to process an entire config set. It shows the details about the amount of time spent pre-processing the configurations, converting them to XCP, and pushing them to the k8s cluster",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(max_over_time(mpc_config_total_process_time{error=\"\", component=\"mpc\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "Total"
    },
    {
     "expr": "sum(max_over_time(mpc_config_pre_process_time{error=\"\", component=\"mpc\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "PreProcessing"
    },
    {
     "expr": "sum(max_over_time(mpc_config_conversion_time{error=\"\", component=\"mpc\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "Conversions"
    },
    {
     "expr": "sum(max_over_time(mpc_xcp_config_push_time{error=\"\", component=\"mpc\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "K8s Push"
    }
   ]
  },
  {
   "title": "Received configs by type",
   "type": "bargauge",
   "description": "Configuration updates received from TSB are processed by MPC and translated into XCP resources. This metric shows the number of objects of each type MPC will convert.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(max_over_time(mpc_tsb_config_received_count{resource!=\"\", component=\"mpc\"}[$mpcTimePeriod])) by(component, resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Total Conversion Time by Type every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Time it takes to convert TSB resources to the XCP APIs.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(mpc_xcp_conversion_duration_sum{component=\"mpc\"}[$mpcTimePeriod])) by (resource)",
     "legendFormat": "{{resource}} P99"
    }
   ]
  },
  {
   "title": "Conversion Time by Type every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Time it takes to convert TSB resources to the XCP APIs.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mpc_xcp_conversion_duration_bucket{}[$mpcTimePeriod])) by (le, resource))",
     "legendFormat": "{{resource}} P99"
    }
   ]
  },
  {
   "title": "Conversions by Resource every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Conversions by resource executed in a time period. This can be used to understand the throughput of the MPC conversions.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mpc_xcp_conversion_duration_count{resource!=\"\", component=\"mpc\"}[$mpcTimePeriod])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Conversions Invalidations by Resource every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Conversions Invalidations by resource executed in a time period. This can be used to understand the throughput of the MPC conversions.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(mpc_xcp_conversion_invalidation_duration_count{component=\"mpc\", resource!=\"\"}[$mpcTimePeriod])) by (resource)",
     "legendFormat": "{{resource}}"
    }
   ]
  },
  {
   "title": "Conversion Invalidation Time every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Time it takes to invalidate TSB resources for a given conversion to the XCP APIs.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(mpc_xcp_conversion_invalidation_duration_bucket{component=\"mpc\", resource!=\"\"}[$mpcTimePeriod])) by (le, resource))",
     "legendFormat": "{{resource}} P99"
    }
   ]
  },
  {
   "title": "Updates from TSB every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Configuration and onboarded cluster messages received from TSB.\n\nThe number of update messages may increase or decrease based on the time it takes for MPC to fully process the messages. The more time it takes to process, the less frequent config updates will be retrieved.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_client_handled_total{component=\"mpc\", grpc_method=\"GetAllConfigObjects\", grpc_code=\"OK\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Config Updates"
    },
    {
     "expr": "sum(increase(grpc_client_handled_total{component=\"mpc\", grpc_method=\"GetAllClusters\", grpc_code=\"OK\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Cluster Updates"
    },
    {
     "expr": "sum(increase(grpc_client_handled_total{component=\"mpc\", grpc_method=\"GetAllConfigObjects\", grpc_code!=\"OK\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Config Updates Error"
    },
    {
     "expr": "sum(increase(grpc_client_handled_total{component=\"mpc\", grpc_method=\"GetAllClusters\", grpc_code!=\"OK\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Cluster Updates Error"
    }
   ]
  },
  {
   "title": "MPC to XCP pushed configs",
   "type": "timeseries",
   "description": "The number of resources that are pushed to XCP.\n\nThis metric shows the number of objects that are created, updated, and deleted as part of a configuration push from MPC to XCP.\nIt also shows how many fetch calls to the k8s api server are done.\n\nThis metric can be used together with the TSB tp MPC sent configs and XCP push operations and push duration to get an understanding of how the amount of resources being pushed to XCP affects the time it takes for the entire configuration push operation to complete.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mpc_xcp_config_create_ops{component=\"mpc\"})",
     "legendFormat": "Creates"
    },
    {
     "expr": "sum(mpc_xcp_config_update_ops{component=\"mpc\"})",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(mpc_xcp_config_delete_ops{component=\"mpc\"})",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(mpc_xcp_config_fetch_ops{component=\"mpc\"})",
     "legendFormat": "Lists"
    }
   ]
  },
  {
   "title": "MCP to XCP pushed configs error",
   "type": "timeseries",
   "description": "The number of resources that failed while pushing to XCP.\n\nThis metric shows the number of objects that fail when they are tried to be created, updated, and deleted as part of a configuration push from MPC to XCP.\nIt also shows the number of failed fetch calls to the k8s api server.\n\nThis metric can be used together with the MPC to TSB push configs and the XCP push operations and push duration to get an understanding of how the amount of resources being pushed to XCP affects the time it takes for the entire configuration push operation to complete.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(mpc_xcp_config_create_ops_err{component=\"mpc\"})",
     "legendFormat": "Creates"
    },
    {
     "expr": "sum(mpc_xcp_config_update_ops_err{component=\"mpc\"})",
     "legendFormat": "Updates"
    },
    {
     "expr": "sum(mpc_xcp_config_delete_ops_err{component=\"mpc\"})",
     "legendFormat": "Deletes"
    },
    {
     "expr": "sum(mpc_xcp_config_fetch_ops_err{component=\"mpc\"})",
     "legendFormat": "Lists"
    }
   ]
  },
  {
   "title": "Config Status updates (XCP -> MPC -> TSB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Config Status updates every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Config Status update messages sent over the gRPC streams, from XCP to MPC to XCP.\n\nThis metric can help understand how messages are queued in TSB when it is under load. The value for both metrics should always be the same. If the Received by TSB metric has a value lower than the MPC one, it means TSB is under load and cannot process all messages sent by MPC as fast as MPC is sending them.\n\n",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_client_msg_received_total{grpc_method=\"Report\",component=\"mpc\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Received by MPC"
    },
    {
     "expr": "sum(increase(grpc_client_msg_sent_total{grpc_method=\"PushStatus\",component=\"mpc\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Sent from MPC"
    },
    {
     "expr": "sum(increase(grpc_server_msg_received_total{grpc_method=\"PushStatus\", component=\"tsb\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Received by TSB"
    }
   ]
  },
  {
   "title": "Config Status updates processed every $mpcTimePeriod",
   "type": "timeseries",
   "description": "This is the number of config status updates that are processed by the Management Plane Controller (MPC), that are received from XCP and to be sent to TSB.\n\nThere are two gRPC streams, one that connects XCP to MPC and another one that connects MPC to TSB.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"StatusPush\", error=\"\", component=\"mpc\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful MPC to TSB ops"
    },
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"StatusPull\", error=\"\", component=\"mpc\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful XCP to MPC ops"
    },
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"StatusPush\", error!=\"\", component=\"mpc\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Errored MPC to TSB ops"
    },
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"StatusPull\", error!=\"\", component=\"mpc\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Errored XCP to MPC ops"
    }
   ]
  },
  {
   "title": "Config Status stream connection attempts every $mpcTimePeriod",
   "type": "timeseries",
   "description": "The number of connection (and reconnection) attempts on the config status updates streams.\nMPC sends the config status updates over a permanently connected gRPC stream to TSB. At the same time, XCP sends them to MPC. This metric shows the number of connections and reconnections that happened on each stream.\n",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"StatusPull\", error=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful XCP to MPC attemps"
    },
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"StatusPull\", error!=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Erroring XCP to MPC attemps"
    },
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"StatusPush\", error=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful MPC to TSB attemps"
    },
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"StatusPush\", error!=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Erroring MPC to TSB attemps"
    }
   ]
  },
  {
   "title": "TSB Handled Status Reports $mpcTimePeriod",
   "type": "timeseries",
   "description": "Number of config status reports handled by TSB.\nEach received config status report is either handled or skipped.\n- Handled: Process and store the status report directly, or if --max-status-report-workers is > 1, enqueued for async processing.\n- Skipped: For duplicated status reports.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(config_handling_duration_count{component=\"tsb\"}[$mpcTimePeriod])) by(skip)",
     "legendFormat": "{{skip}}"
    }
   ]
  },
  {
   "title": "Config status cache operations every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Number of operations done in the config status cache when receiving new config statuses.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_msg_received_total{grpc_method=\"PushStatus\", component=\"tsb\"}[$mpcTimePeriod]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(increase(config_status_cache_check_total{}[$mpcTimePeriod]))",
     "legendFormat": "Checks"
    },
    {
     "expr": "sum(increase(config_status_cache_add_total{error=\"false\"}[$mpcTimePeriod]))",
     "legendFormat": "Adds"
    },
    {
     "expr": "sum(increase(config_status_cache_invalidate_total{}[$mpcTimePeriod]))",
     "legendFormat": "Invalidates"
    },
    {
     "expr": "sum(increase(config_status_cache_check_total{error=\"true\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Checks errored"
    },
    {
     "expr": "sum(increase(config_status_cache_add_total{error=\"true\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Adds errored"
    }
   ]
  },
  {
   "title": "TSB Processed Status Reports in $mpcTimePeriod",
   "type": "timeseries",
   "description": "The number of config status reports processed by TSB.\nThis number must be the same as the number of handled ones without the skipped ones.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(config_status_report_work_duration_bucket{component=\"tsb\"}[$mpcTimePeriod])) by (le, skip))",
     "legendFormat": "{{skip}}"
    }
   ]
  },
  {
   "title": "TSB Handling Status Reports Duration $mpcTimePeriod",
   "type": "timeseries",
   "description": "The P99 duration in milliseconds of  handling a received status reports handled by TSB.\nEach received config status report is either handled or skipped.\n- Handled: Process and store the status report directly, or if --max-status-report-workers is > 1, enqueued for async processing.\n- Skipped: For duplicated status reports.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(config_handling_duration_bucket{component=\"tsb\"}[$mpcTimePeriod])) by (le, skip))",
     "legendFormat": "{{skip}}"
    }
   ]
  },
  {
   "title": "Config status cache operations by event type every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Number of operations done in the cache by event type.\n\nThis metric helps understand the amount of event processing that can be skipped on the TSB side when receiving events because TSB already knows about them, and help understand how status event reporting relates to load on the TSB side.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(config_status_cache_check_total{error=\"false\", component=\"tsb\"}[$mpcTimePeriod])) by (type)",
     "legendFormat": " CHECK {{type}}"
    },
    {
     "expr": "sum(increase(config_status_cache_add_total{error=\"false\", component=\"tsb\"}[$mpcTimePeriod])) by (type)",
     "legendFormat": "ADD {{type}}"
    }
   ]
  },
  {
   "title": "TSB Processing Status Reports Duration $mpcTimePeriod",
   "type": "timeseries",
   "description": "The P99 duration in milliseconds of  processing config status reports handled by TSB.\nProcessing of a config status report involves analyse, apply/storing the result, propagate to parents and dependants.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(config_status_report_work_duration_bucket{component=\"tsb\"}[$mpcTimePeriod])) by (le, skip))",
     "legendFormat": "{{skip}}"
    }
   ]
  },
  {
   "title": "Status Reports Work per Shard Distribution",
   "type": "heatmap",
   "description": "Only applies when tsb --max-status-report-workers is > 1.\nDistribution of the status report work across the different shards.\n",
   "gridPos": { "h": 23, "w": 8, "x": 0, "y": 69 },
   "targets": [
    {
     "expr": "sum(increase(sharded_queue_work_duration_count{name=\"status-reports\", component=\"tsb\"}[$mpcTimePeriod])) by (component, shard)",
     "legendFormat": "{{shard}}"
    }
   ]
  },
  {
   "title": "Work executions every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Only applies when tsb --max-status-report-workers is > 1.\nAmount of status processing jobs processed",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(sharded_queue_work_duration_count{component=\"tsb\"}[$mpcTimePeriod])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Status updates worker time every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Only applies when tsb --max-status-report-workers is > 1.\nTime it takes for workers to process a single status update event.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sharded_queue_work_duration_bucket{}[$mpcTimePeriod])) by (le, name))",
     "legendFormat": "Worker duration P99 {{name}}"
    }
   ]
  },
  {
   "title": "TSB Status Updates Enqueue Delay $mpcTimePeriod",
   "type": "timeseries",
   "description": "Only applies when tsb --max-status-report-workers is > 1.\nThe P99 delay is milliseconds since a config status report started the enqueuing until the queue accepted(enqueued) the config status report.\n\nIf the P99 delay goes high it means that that a shard of the queue is filled up reaching its max capacity.\nIf it goes over minutes, it means that there is deadlock probably.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sharded_queue_enqueue_delay_bucket{name=\"status-reports\"}[$mpcTimePeriod])) by (le, name))",
     "legendFormat": "Worker duration P99 {{name}}"
    }
   ]
  },
  {
   "title": "TSB Status Updates Enqueue Delay $mpcTimePeriod",
   "type": "heatmap",
   "description": "Only applies when tsb --max-status-report-workers is > 1.\nThe delay is milliseconds since a config status report started the enqueuing until the queue accepted(enqueued) the config status report.\n\nThe config status report queue has a fixed size of element in can't hold per bucket. \nIf the enqueuing latency goes up, it means that there is contention in the queue and more elements cannot be placed until the queue releases spaces by consuming its enqueued elements.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 76 },
   "targets": [
    {
     "expr": "sum(rate(sharded_queue_enqueue_delay_bucket{name=\"status-reports\"}[$mpcTimePeriod])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "TSB Status Updates Worker Delay $mpcTimePeriod",
   "type": "timeseries",
   "description": "Only applies when tsb --max-status-report-workers is > 1.\nThe delay is milliseconds since a config status report is received and processed by the work queue.",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(sharded_queue_work_delay_bucket{name=\"status-reports\"}[$mpcTimePeriod])) by (le, name))",
     "legendFormat": "Worker duration P99 {{name}}"
    }
   ]
  },
  {
   "title": "TSB Status Updates Worker Delay $mpcTimePeriod",
   "type": "heatmap",
   "description": "Only applies when tsb --max-status-report-workers is > 1.\nThe delay is milliseconds since a config status report is received and processed by the work queue.",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 83 },
   "targets": [
    {
     "expr": "sum(rate(sharded_queue_work_delay_bucket{name=\"status-reports\"}[$mpcTimePeriod])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Cluster Updates (XCP -> MPC -> TSB)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 92 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Cluster Status Update from XCP every $mpcTimePeriod",
   "type": "timeseries",
   "description": "Cluster status update messages received from XCP over a gRPC stream.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_client_msg_received_total{component=\"mpc\", grpc_method=\"GetClusterState\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Received by MPC"
    }
   ]
  },
  {
   "title": "Cluster updates from XCP  processed every $mpcTimePeriod",
   "type": "timeseries",
   "description": "The number of cluster status updates received by the Management Plane Controller (MPC) from XCP that must be processed and sent to TSB.\n\nXCP sends the cluster status updates (e.g. services deployed in the cluster) over a permanently connected gRPC stream to MPC. This metric shows the number of messages received and processed by MPC on that stream.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"ClusterStateFromXCP\", error=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"ClusterStateFromXCP\", error!=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "XCP cluster status updates Sent to TSB every $mpcTimePeriod",
   "type": "timeseries",
   "description": "This is the number of cluster status updates that are processed by the Management Plane Controller (MPC) to be sent to TSB.\n\nMPC sends the cluster status updates over a gRPC stream that is permanently connected to TSB, and this metric shows the number of cluster updates that are processed by MPC and sent to TSB on that stream.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"ClusterUpdates\", error=\"\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(permanent_stream_operation_total{name=\"ClusterUpdates\", error!=\"\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Cluster status updates to TSB stream connection attempts every $mpcTimePeriod",
   "type": "timeseries",
   "description": "The number of connection (and reconnection) attempts on the cluster status updates stream.\nMPC sends the cluster status updates over a permanently connected gRPC stream to TSB. This metric shows the number of connections and reconnections that happened on that stream.\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"ClusterUpdates\", error=\"\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"ClusterUpdates\", error!=\"\"}[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  {
   "title": "Cluster updates from XCP stream connection attempts every $mpcTimePeriod",
   "type": "timeseries",
   "description": "The number of connection (and reconnection) attempts on the cluster status updates from XCP stream.\nXCP sends the cluster status updates over a permanently connected gRPC stream to MPC. This metric shows the number of connections and reconnections that happened on that stream.\n",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"ClusterStateFromXCP\", error=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Successful"
    },
    {
     "expr": "sum(increase(permanent_stream_connection_attempts_total{name=\"ClusterStateFromXCP\", error!=\"\" }[$mpcTimePeriod])) or on() vector(0)",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "GC Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "GC Count by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 120 },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_count{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "GC Duration by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod]) / rate(go_gc_duration_seconds_count{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])) by (component)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Allocations by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_memstats_heap_alloc_bytes{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Objects by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_memstats_heap_objects{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])) by (component)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Next GC Target by Component in Management Plane",
   "type": "timeseries",
   "description": "The heap memory size during the next GC cycle. GC is used to guarantee that the value is no less than the value of ",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_memstats_next_gc_bytes{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])) by (component)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Utilization Percentage  by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 140 },
   "targets": [
    {
     "expr": "(\n  sum(go_memstats_heap_inuse_bytes{component=\"xcp\"}) by (component) /\n  sum(go_memstats_heap_idle_bytes{component=\"xcp\"} + go_memstats_heap_inuse_bytes{component=\"xcp\"}) by (component)\n) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  sum(go_memstats_heap_inuse_bytes{component=\"tsb\"}) by (component) /\n  sum(go_memstats_heap_idle_bytes{component=\"tsb\"} + go_memstats_heap_inuse_bytes{component=\"tsb\"}) by (component)\n) * 100",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n  sum(go_memstats_heap_inuse_bytes{component=\"mpc\"}) by (component) /\n  sum(go_memstats_heap_idle_bytes{component=\"mpc\"} + go_memstats_heap_inuse_bytes{component=\"mpc\"}) by (component)\n) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC CPU Fraction  by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(\n  rate(go_gc_duration_seconds_sum{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod]) /\n  rate(process_cpu_seconds_total{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])\n) by (component)* 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Goroutines  by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 150 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_goroutines{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heap Sys by Component in Management Plane",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_memstats_heap_sys_bytes{component=~\"tsb|mpc|xcp\", plane=\"management\"}[$mpcTimePeriod])) by (component)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "GRPC / HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "gRPC Server Calls Started Rate",
   "type": "timeseries",
   "description": "The rate of RPCs started on the server.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_started_total{component=\"tsb\", grpc_method=~\"GetAllClusters|UpdateClusterState|GetAllConfigObjects\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Server Handled Rate",
   "type": "timeseries",
   "description": "The rate of RPCs completed on the server.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 169 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{component=\"tsb\", grpc_method=~\"GetAllClusters|UpdateClusterState|GetAllConfigObjects\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client Calls Started Rate",
   "type": "timeseries",
   "description": "The rate of the RPCs started on the client.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_started_total{component=\"mpc\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client Handled Rate",
   "type": "timeseries",
   "description": "The rate of RPCs completed on the client.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 177 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_handled_total{component=\"mpc\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Server Handled Status Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 185 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{component=\"tsb\", grpc_method=~\"GetAllClusters|UpdateClusterState|GetAllConfigObjects\"}[$mpcTimePeriod])) by (component, grpc_code)",
     "legendFormat": "{{grpc_code}} {{component}}"
    }
   ]
  },
  {
   "title": "gRPC Client Handled Status Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 185 },
   "targets": [
    {
     "expr": "max(rate(grpc_client_handled_total{component=\"mpc\"}[$mpcTimePeriod])) by (grpc_code, component)",
     "legendFormat": "{{grpc_code}} {{component}}"
    }
   ]
  },
  {
   "title": "gRPC Server Msg Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{component=\"tsb\", grpc_method=~\"GetAllClusters|UpdateClusterState|GetAllConfigObjects\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client Msg Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 193 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_client_msg_received_total{component=\"mpc\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Client Msg Sent Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_msg_sent_total{component=\"tsb\", grpc_method=~\"GetAllClusters|UpdateClusterState|GetAllConfigObjects\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  },
  {
   "title": "gRPC Server Msg Received Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 201 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(grpc_server_msg_received_total{component=\"tsb\", grpc_method=~\"GetAllClusters|UpdateClusterState|GetAllConfigObjects|PushStatus\"}[$mpcTimePeriod])) by (grpc_method, component)",
     "legendFormat": "{{component}}/{{grpc_method}}"
    }
   ]
  }
 ]
}