{
 "title": "TSB Health",
 "description": "TSB Health fast diagnosis",
 "tags": [
  "tsb",
  "health"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "TSB Core Components Health Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "MPC Health",
   "type": "stat",
   "description": "MPC Health Status.\nThree metrics define the health of this component:\n1. If mpc_info stops reporting, then it is KO.\n2. If mpc has create operations errors, then it is degraded (!!!).\n3. If mpc has fetch operations errors, then it is degraded (!!!).\n4. If mpc gRPC streams had more than X errors, then it is degraded (!!!)\n\nIf 2 and 3, then it is KO\n\n",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$A + ($B*0.5) + ($C*0.5) + ($D*0.4)",
     "type": "math"
    }
   ]
  },
  {
   "title": "XCP Central Health",
   "type": "stat",
   "description": "CentralXCP Health Status.\n1. If the number of grpc connections from Central to edges and MPC is less than 1, then KO. Edge connections of type cluster_state should be 1 for tsb api and 1 for each cluster. Because in previous versions we had some scenarios with negative values, we account for it with the less tha 1. \n2. If the propagation time is greater than 10 seconds, it is degraded (!!!). If it is equal or greater than 20 seconds, then it is KO.",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "conditions": [
      {
       "evaluator": {
        "params": [
         0,
         0
        ],
        "type": "gt"
       },
       "operator": { "type": "and" },
       "query": {
        "params": []
       },
       "reducer": {
        "params": [],
        "type": "avg"
       },
       "type": "query"
      }
     ],
     "downsampler": "mean",
     "expression": "$A + $B/30000",
     "reducer": "mean",
     "type": "math",
     "upsampler": "fillna"
    }
   ]
  },
  {
   "title": "XCP Edge Health",
   "type": "stat",
   "description": "XCP Edge Health\n1. This is a key metric about messages received by central from edges. If some of the edges stop reporting, there's a problem with the edges.\n2. This is a key metric about time passed since edges synced with central. If it is more than 10 minutes, there's a problem with one of the edges.\n\n",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  { "title": "TSB Non-Core Health Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "TSB API Health",
   "type": "stat",
   "description": "TSB API Health Status.\n1. If OK grpc codes reported by TSB API are 0 or not being reported, this silence indicates an error. IF KO, use tctl or UI to check if tsb api is returning. If everything's alright, any call should set this metric to OK.\n",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A", "type": "math" }
   ]
  },
  {
   "title": "IAM Health",
   "type": "stat",
   "description": "IAM Health Status.\n1. If no authentication operations are reported, IAM is having an issue.\n2. If the difference between the short and middle term latencies for JWT is more than 1 second, then IAM is degraded.\n3. If the difference between the short and middle term latencies for JWT is more than 5 seconds, then IAM is having an issue.\n4. If the difference between the short and middle term latencies for non-JWT is more than 5 seconds, then IAM is degraded.\n5. If the difference between the short and middle term latencies for non-JWT is more than 30 seconds, then IAM is having an issue.\n",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expression": "$A + ($B*0.5) + $C + ($D*0.5) + $E",
     "type": "math"
    }
   ]
  },
  {
   "title": "OAP Health",
   "type": "stat",
   "description": "OAP Health Status.\n1. If OAP's JVM are not reported, then OAP in the management plane has an issue.\n2. If the number of reporting clusters to xcp central is less than the number of control planes OAPs, theres an issue with one or more OAPs in the CPs. The dependency on xcp central health is controlled by only accounting for positive differences.",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "$A + $B", "type": "math" }
   ]
  },
  {
   "title": "Front Envoy Health",
   "type": "stat",
   "description": "Front Envoy Health Status.\n1.If the difference between the short and the long average response time from its upstream transactions exceeds a given threshold in ms (defined by the divisor).\n",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "abs($A - $B) / 1000", "type": "math" }
   ]
  }
 ]
}