{
 "title": "TSB Operational Status",
 "description": "Operational metrics to indicate Tetrate Service Bridge API server health.",
 "tags": [
  "tsb",
  "iam",
  "front-envoy",
  "ngac"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "Management Plane Front Envoy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Front Envoy Success Rate",
   "type": "timeseries",
   "description": "Rate of successful requests to Front Envoy. This includes all user and cluster requests into the management plane.\n\nNote: This indicates the health of the AuthZ server not whether the user or cluster making the request has the correct permissions.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_internal_upstream_rq_total{envoy_response_code=~\"2.*|3.*|401\", component=\"front-envoy\"}[1m])) by (envoy_cluster_name)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Front Envoy Error Rate",
   "type": "timeseries",
   "description": "The error rate of requests to the Front Envoy server. This includes all user and cluster requests into the management plane.\nNote: This indicates the health of the AuthZ server not whether the user or cluster making the request has the correct permissions.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_internal_upstream_rq_total{envoy_response_code!~\"2.*|3.*|401\", component=\"front-envoy\"}[1m])) by (envoy_cluster_name, envoy_response_code)",
     "legendFormat": "{{envoy_cluster_name}}"
    }
   ]
  },
  {
   "title": "Front Envoy Latency",
   "type": "timeseries",
   "description": "Front Envoy request latency percentiles.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(envoy_cluster_internal_upstream_rq_time_bucket{component=\"front-envoy\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_internal_upstream_rq_time_bucket{component=\"front-envoy\"}[1m])) by (le, envoy_cluster_name))",
     "legendFormat": "{{envoy_cluster_name}} P95"
    }
   ]
  },
  { "title": "API Server Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "TSB Success Rate",
   "type": "timeseries",
   "description": "Rate of successful requests to the TSB apiserver from the UI and CLI.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{component=\"tsb\", grpc_code=\"OK\", grpc_type=\"unary\", grpc_method!=\"SendAuditLog\"}[1m])) by (grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  {
   "title": "TSB Error Rate",
   "type": "timeseries",
   "description": "Rate of failed requests to the TSB apiserver from the UI and CLI.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(grpc_server_handled_total{component=\"tsb\", grpc_code!=\"OK\", grpc_type=\"unary\", grpc_method!=\"SendAuditLog\"}[1m])) by (grpc_code, grpc_method)",
     "legendFormat": "{{grpc_method}}"
    }
   ]
  },
  { "title": "Authentication", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Authentication Success Rate",
   "type": "timeseries",
   "description": "The success rate for authentication operations for each type of authentication provider.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(iam_auth_time_count{error=\"\"}[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Authentication Error Rate",
   "type": "timeseries",
   "description": "The error rate for authentication operations for each type of authentication provider.\n\nSpikes may indicate problems with the provider or the given credentials, such as expired JWT tokens.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(iam_auth_time_count{error!=\"\"}[1m])) by (provider)",
     "legendFormat": "{{provider}}"
    }
   ]
  },
  {
   "title": "Authentication Latency",
   "type": "timeseries",
   "description": "The latency for authentication operations for each type of authentication provider.\n\nSpikes in the latency may indicate that the authentication provider has a sub-optimal configuration (such as too wide LDAP queries).",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(iam_auth_time_bucket{error=\"\"}[1m])) by (le, provider))",
     "legendFormat": "{{provider}} P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(iam_auth_time_bucket{error=\"\"}[1m])) by (le, provider))",
     "legendFormat": "{{provider}} P95"
    }
   ]
  },
  { "title": "Data Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Data Store Operations Rate",
   "type": "timeseries",
   "description": "Request rate for operations persisting data to the datastore grouped by method and kind.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(persistence_operation_total[1m])) by (kind, method)",
     "legendFormat": "{{method}} / {{kind}}"
    }
   ]
  },
  {
   "title": "Data Store Operations Error Rate",
   "type": "timeseries",
   "description": "The request error rate for operations persisting data to the datastore grouped by method and kind.\nThis graph also includes transactions. These are standard SQL transactions and consists of multiple operations.\nNote: The graph explicitly excludes \"resource not found\" errors. A small number of \"not found\" responses are normal as TSB for optimization often uses Get queries instead of Exists to determine the resource existence.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(persistence_operation_total{error=\"true\", kind!=\"iam_revoked_token\"}[1m])) by (kind, method, error)",
     "legendFormat": "{{method}} / {{kind}}"
    }
   ]
  },
  {
   "title": "Data Store Operations Latency",
   "type": "timeseries",
   "description": "The request latency for operations persisting data to the datastore grouped by method.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(persistence_operation_duration_bucket{}[1m])) by (le, method))",
     "legendFormat": "{{method}} P99"
    }
   ]
  },
  {
   "title": "Data Store Transaction Rate",
   "type": "timeseries",
   "description": "The rate of newly creates transactions dry run mode. These are standard SQL transactions and consist of multiple operations.\n",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(persistence_transaction_total[1m])) by (dry_run_mode)",
     "legendFormat": "{{dry_run_mode}}"
    }
   ]
  },
  {
   "title": "Data Store Transaction Error Rate",
   "type": "timeseries",
   "description": "The rate of  transactions that failed at execution time by dry run mode. These are standard SQL transactions and consist of multiple operations.\n",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(persistence_transaction_total{error=\"true\"}[1m])) by (dry_run_mode)",
     "legendFormat": "{{dryRunMode}}"
    }
   ]
  },
  {
   "title": "Data Store Transactions Latency",
   "type": "timeseries",
   "description": "TheP99 latency of transactions execution grouped by dry run mode.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(persistence_transaction_duration_bucket[1m])) by (le, dry_run_mode))",
     "legendFormat": "{{dry_run_mode}} P99"
    }
   ]
  },
  {
   "title": "Active Transactions",
   "type": "timeseries",
   "description": "The number of running transactions on the datastore.\n\nThis graph shows how many active transactions are running at a given point in time. It helps you understand the load of the system generated by concurrent access to the platform.\n",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(persistence_concurrent_transaction{}) by (dry_run_mode)",
     "legendFormat": "Active Tx {{dry_run_mode}}"
    }
   ]
  },
  {
   "title": "Mismatching Transactions dry run mode",
   "type": "timeseries",
   "description": "This is the number of child transactions that do not match parent's transaction dry run mode.\n\nThis means that the dry run mode has not properly been propagated to child transactions.",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(persistence_dry_run_transaction_mismatch_total)",
     "legendFormat": "Mismaches"
    }
   ]
  },
  { "title": "Database Pool", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "In Use Connections",
   "type": "timeseries",
   "description": "The number of connections currently in use.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_in_use_connections{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Open Connections/Max Connections",
   "type": "timeseries",
   "description": "The number of established connections both in use and idle. Also the maximum allowed number of connections is displayed.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_open_connections{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "Open {{component}}"
    },
    {
     "expr": "sum(max_over_time(go_sql_max_open_connections{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "Max Allowed {{component}}"
    }
   ]
  },
  {
   "title": "Connections Waited",
   "type": "timeseries",
   "description": "The total number of connections waited for.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(go_sql_wait_count_total{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Time Waiting for Connections",
   "type": "timeseries",
   "description": "The total time blocked waiting for a new connection.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(increase(go_sql_wait_duration_seconds_total{component=\"tsb\", db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Created Connections",
   "type": "timeseries",
   "description": "The number of created connections",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(db_sql_created_connections_duration_count{}[1m])) by (component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Create Connections Latency",
   "type": "timeseries",
   "description": "The p99 duration in milliseconds for creating new connection.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(db_sql_created_connections_duration_bucket{}[1m])) by (le, component))",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "Closed Connections",
   "type": "timeseries",
   "description": "The number of closed connections by reasons.\n- Max Idle: The total number of connections closed due to SetMaxIdleConns.\n- Idle Time: The total number of connections closed due to SetConnMaxIdleTime.\n- Max Lifetime: The total number of connections closed due to SetConnMaxLifetime.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(increase(go_sql_max_idle_closed_total{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "Max Idle {{component}}"
    },
    {
     "expr": "sum(increase(go_sql_max_idle_time_closed_total{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "Idle Time {{component}}"
    },
    {
     "expr": "sum(increase(go_sql_max_lifetime_closed_total{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "Max Lifetime {{component}}"
    }
   ]
  },
  {
   "title": "Idle Connections",
   "type": "timeseries",
   "description": "The number of idle connections.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(max_over_time(go_sql_idle_connections{db_name=\"dbpool\"}[$__rate_interval])) by(component)",
     "legendFormat": "{{component}}"
    }
   ]
  },
  { "title": "Service Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 83 } },
  {
   "title": "Service Registry Operations",
   "type": "timeseries",
   "description": "This metric shows the amount of operations done by the service registry. The service registry will handle all service changes across the clusters, detecting and persisting them in the database.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "targets": [
    {
     "expr": "sum(increase(service_registry_operation_duration_count{error=\"\"}[1m])) by (operation)",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "sum(increase(service_registry_operation_duration_count{error!=\"\"}[1m])) by (operation)",
     "legendFormat": "{{operation}} errors"
    }
   ]
  },
  {
   "title": "Service Registry Operations Duration",
   "type": "timeseries",
   "description": "Duration of operations performed by the service registry.\n\nThis graph also includes the total duration of the reconciliation process during which the service registry iterates through all clusters to identify changes that need to be persisted in the database.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(service_registry_operation_duration_bucket{}[1m])) by (le, operation))",
     "legendFormat": "{{operation}} P99"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(service_registry_total_duration_bucket{}[1m])) by (le))",
     "legendFormat": "Total reconciliation P99"
    }
   ]
  },
  { "title": "NGAC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 91 } },
  {
   "title": "PDP Success Rate",
   "type": "timeseries",
   "description": "Successful request rate of PDP grouped by method.\nNGAC is a graph-based authorization framework that consists of three main components:\nPolicy Information Point (PIP): Maintains the NGAC graph. It creates the nodes and edges in the graph that represents the state of the system. The other components of NGAC use this graph to perform access decisions.\nPolicy Decision Point (PDP): Performs access decisions based on the NGAC graph's policies. The PDP is used to perform binary Allow/Deny access decisions (Check) and determine the objects a user has access to (List). These access decisions are enforced at the Policy Enforcement Point (PEP).\nPolicy Enforcement Point (PEP): Enforces access control by calling the PDP to get an access decision. Successful requests to the PDP show the number of requests that the PEP has successfully made to the PDP. A successful request does not represent \"access granted\" decisions; they represent the access decision requests for which a verdict was obtained.\nA drop in this metric may show that operations against the graph are failing. This may mean that the graph is unavailable for reads and this is usually a consequence of failures in the PIP. Failures in the PIP for write operations will result in the graph not being properly updated to the latest status, resulting in access decisions based on stale models.\n",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ngac_pdp_operation_total{error=\"\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "PDP Error Rate",
   "type": "timeseries",
   "description": "Rate of errors for PDP requests grouped by method.\nNGAC is a graph-based authorization framework that consists of three main components:\nPolicy Information Point (PIP): Maintains the NGAC graph. It creates the nodes and edges in the graph that represents the state of the system. The other components of NGAC use this graph to perform access decisions.\nPolicy Decision Point (PDP): Performs access decisions based on the NGAC graph's policies. The PDP is used to perform binary Allow/Deny access decisions (Check) and determine the objects a user has access to (List). These access decisions are enforced at the Policy Enforcement Point (PEP).\nPolicy Enforcement Point (PEP): Enforces access control by calling the PDP to get an access decision. Successful requests to the PDP show the number of requests that the PEP has successfully made to the PDP. A successful request does not represent \"access granted\" decisions; they represent the access decision requests where a verdict was obtained.\nFailed requests to the PDP show the number of requests from the PEP to the PDP that have failed. They do not represent \"access denied\" decisions; they represent the access decision requests where a verdict could not be obtained.\nA rise in this metric may show that operations against the graph are failing. This may mean that the graph is unavailable for reads and this is usually a consequence of failures in the PIP. Failures in the PIP for write operations will result in the graph not being correctly updated to the latest status, resulting in access decisions based on stale models.\n",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ngac_pdp_operation_total{error!=\"\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "PDP Latency",
   "type": "timeseries",
   "description": "PDP latency percentiles grouped by method.\nNGAC is a graph-based authorization framework that consists of three main components:\nPolicy Information Point (PIP): Maintains the NGAC graph. It creates the nodes and edges in the graph that represents the state of the system. The other components of NGAC use this graph to perform access decisions.\nPolicy Decision Point (PDP): Performs access decisions based on the NGAC graph's policies. The PDP is used to perform binary Allow/Deny access decisions (Check) and determine the objects a user has access to (List). These access decisions are enforced at the Policy Enforcement Point (PEP).\nPolicy Enforcement Point (PEP): Enforces access control by calling the PDP to get an access decision. Successful requests to the PDP show the number of requests that the PEP has successfully made to the PDP. A successful request does not represent \"access granted\" decisions; they represent the access decision requests for which a verdict was obtained.\nThis metric shows the time it takes to get an access decision for authorization requests.\nDegradation in PDP operations may result in general degradation of the system. PDP latency represents the time it takes to make access decisions, and that will impact user experience since access decisions are made and enforced for every operation.\n",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ngac_pdp_operation_duration_bucket{}[1m])) by (method, le))",
     "legendFormat": "{{method}} P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ngac_pdp_operation_duration_bucket{}[1m])) by (method, le))",
     "legendFormat": "{{method}} P95"
    }
   ]
  },
  {
   "title": "PIP Success Rate",
   "type": "timeseries",
   "description": "Successful request rate of PIP grouped by method.\n\nNGAC is a graph based authorization framework that consists on three main components:\n\n* Policy Information Point (PIP): Maintains the NGAC graph. It creates the nodes and edges in the graph that represents the state of the system. This graph is used by the other components of NGAC to perform access decisions.\n* Policy Decision Point (PDP): Performs access decisions based on the policies configured in the NGAC graph. The PDP is used to perform binary Allow/Deny access decisions (Check), and to determine the objects a user has access to (List). These access decisions are enforced at the Policy Enforcement Point (PEP).\n* Policy Enforcement Point (PEP): Enforces access control by calling the PDP to get an access decision. Successful requests to the PDP show the number of requests that the PEP has successfully made to the PDP. Successful request do not represent \"access granted\" decisions; they just represent the access decision requests for which a verdict was obtained.\n\nPIP operations are executed against the NGAC graph to represent and maintain the objects in the system and the relationships between them.\n\nA drop in this metric may show that operations against the graph are failing. This may mean that the graph is unavailable for reads, or that it is failing to persist data. Read failures may result in failed access decisions (in the PDP) and user interaction with the system may be rejected as well. Failures in write operations will result in the graph not being properly updated to the latest status and that could result in access decisions based on stale models.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ngac_pip_operation_total{error=\"\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "PIP Latency",
   "type": "timeseries",
   "description": "PiP latency percentiles grouped by method.\n\nNGAC is a graph based authorization framework that consists on three main components:\n\n* Policy Information Point (PIP): Maintains the NGAC graph. It creates the nodes and edges in the graph that represents the state of the system. This graph is used by the other components of NGAC to perform access decisions.\n* Policy Decision Point (PDP): Performs access decisions based on the policies configured in the NGAC graph. The PDP is used to perform binary Allow/Deny access decisions (Check), and to determine the objects a user has access to (List). These access decisions are enforced at the Policy Enforcement Point (PEP).\n* Policy Enforcement Point (PEP): Enforces access control by calling the PDP to get an access decision. Successful requests to the PDP show the number of requests that the PEP has successfully made to the PDP. Successful request do not represent \"access granted\" decisions; they just represent the access decision requests for which a verdict was obtained.\n\nThis metric shows the time it takes for a PIP operation to complete and, in the case of write operations, to have data persisted in the NGAC graph.\n\nDegradation in PIP operations may result in general degradation of the system. PIP latency represents the time it takes to access the NGAC graph, and this directly affects the PDP when running access decisions. A degraded PIP may result in a degraded PDP, and that will impact user experience, as access decisions are made and enforced for every operation.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(ngac_pip_operation_duration_bucket{}[1m])) by (method, le))",
     "legendFormat": "{{method}} P99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ngac_pip_operation_duration_bucket{}[1m])) by (method, le))",
     "legendFormat": "{{method}} P95"
    }
   ]
  },
  {
   "title": "PIP Error Rate",
   "type": "timeseries",
   "description": "Rate of errors for PIP requests grouped by method.\n\nNGAC is a graph based authorization framework that consists on three main components:\n\n* Policy Information Point (PIP): Maintains the NGAC graph. It creates the nodes and edges in the graph that represents the state of the system. This graph is used by the other components of NGAC to perform access decisions.\n* Policy Decision Point (PDP): Performs access decisions based on the policies configured in the NGAC graph. The PDP is used to perform binary Allow/Deny access decisions (Check), and to determine the objects a user has access to (List). These access decisions are enforced at the Policy Enforcement Point (PEP).\n* Policy Enforcement Point (PEP): Enforces access control by calling the PDP to get an access decision. Successful requests to the PDP show the number of requests that the PEP has successfully made to the PDP. Successful request do not represent \"access granted\" decisions; they just represent the access decision requests for which a verdict was obtained.\n\nPIP operations are executed against the NGAC graph to represent and maintain the objects in the system and the relationships between them.\n\nNote: the \"Node not found\" errors are explicitly excluded as TSB often uses `GetNode` method instead of `Exists` to determine the node existence, for the purposes of optimisation.\n\nA general raise in this metric may show that operations against the graph are failing. This may mean that the graph is unavailable for reads, or that it is failing to persist data. Read failures may result in failed access decisions (in the PDP) and user interaction with the system may be rejected as well. Failures in write operations will result in the graph not being properly updated to the latest status and that could result in access decisions based on stale models.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(ngac_pip_operation_total{error!=\"\", error!=\"Node not found\"}[1m])) by (method)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Active PIP Transactions",
   "type": "timeseries",
   "description": "The number of running transactions on the NGAC PIP.\nNGAC is a graph-based authorization framework that consists on three main components:\nPolicy Information Point (PIP): Maintains the NGAC graph. It creates the nodes and edges in the graph that represents the state of the system. The other components of NGAC use this graph to perform access decisions.\nPolicy Decision Point (PDP): Performs access decisions based on the NGAC graph's policies. The PDP is used to perform binary Allow/Deny access decisions (Check) and determine the objects a user has access to (List). These access decisions are enforced at the Policy Enforcement Point (PEP).\nPolicy Enforcement Point (PEP): Enforces access control by calling the PDP to get an access decision. Successful requests to the PDP show the number of requests that the PEP has successfully made to the PDP. A successful request does not represent \"access granted\" decisions; they represent the access decision requests for which a verdict was obtained.\nThis metric shows the number of active write operations against the NGAC graph. It can be useful to understand the load of the system generated by concurrent access to the platform.\n",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(ngac_pip_concurrent_transaction{})",
     "legendFormat": "Active PIP Tx Count"
    }
   ]
  }
 ]
}