{
 "title": "TSB webhooks",
 "description": "Operational status of the Tetrate Service Bridge webhooks",
 "tags": [
  "tsb",
  "xcp"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "Management Plane webhook requests",
   "type": "timeseries",
   "description": "Shows the rate of requests for the webhooks in each management plane component",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(component) (rate(controller_runtime_webhook_requests_total{plane=\"management\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control Plane webhooks requests",
   "type": "timeseries",
   "description": "Shows the rate of requests for the webhooks in each control plane component for the selected cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(component) (rate(controller_runtime_webhook_requests_total{plane=\"control\", cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Management Plane webhook latency",
   "type": "timeseries",
   "description": "Shows the latency percentiles across all management plane webhooks",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(controller_runtime_webhook_latency_seconds_bucket{plane=\"management\"}[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(controller_runtime_webhook_latency_seconds_bucket{plane=\"management\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(controller_runtime_webhook_latency_seconds_bucket{plane=\"management\"}[1m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Control Plane webhook latency",
   "type": "timeseries",
   "description": "Shows the latency percentiles across all control plane webhooks for the selected cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(controller_runtime_webhook_latency_seconds_bucket{plane=\"control\", cluster_name=\"$cluster\"}[1m])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(controller_runtime_webhook_latency_seconds_bucket{plane=\"control\", cluster_name=\"$cluster\"}[1m])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(controller_runtime_webhook_latency_seconds_bucket{plane=\"control\", cluster_name=\"$cluster\"}[1m])))",
     "legendFormat": "P99"
    }
   ]
  },
  {
   "title": "Management Plane deletion protection webhook",
   "type": "timeseries",
   "description": "Shows the number of deletion requests denied and invalid requests received by the deletion protection webhook in the management plane",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(component) (rate(deletion_protection_webhook_denied_total{plane=\"management\"}[1m]))",
     "legendFormat": "{{component}} denied"
    },
    {
     "expr": "sum by(component) (rate(deletion_protection_webhook_invalid_total{plane=\"management\"}[1m]))",
     "legendFormat": "{{component}} invalid"
    }
   ]
  },
  {
   "title": "Control Plane deletion protection webhooks",
   "type": "timeseries",
   "description": "Shows the number of deletion requests denied and invalid requests received by the deletion protection webhook in the control plane for the selected cluster",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(component) (rate(deletion_protection_webhook_denied_total{plane=\"control\", cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "{{component}} denied"
    },
    {
     "expr": "sum by(component) (rate(deletion_protection_webhook_invalid_total{plane=\"control\", cluster_name=\"$cluster\"}[1m]))",
     "legendFormat": "{{component}} invalid"
    }
   ]
  }
 ]
}