{
 "title": "XCP Central Operational Status",
 "description": "Operational metrics to indicate XCP Central health.",
 "tags": [
  "tsb",
  "xcp",
  "central"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{component=\"xcp\",plane=\"management\"}"
    }
   ]
  },
  {
   "title": "XCP Central Version",
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "label_replace(xcp_central_version{}, \"xcp_version\", \"$1\", \"version\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "XCP Central",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Time since last cluster state received from the edge (seconds)",
   "type": "bargauge",
   "description": "Since the default cluster state resync time is 10 minutes, any value higher than 600-700 seconds is considered abnormal.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(max((increase(xcp_central_current_onboarded_edge_total[2m]) unless increase(xcp_central_current_onboarded_edge_total[2m]) == 0)) by (edge) + on(edge) group_right xcp_central_last_config_propagation_event_timestamp_ms{edge!=\"\", status=\"received\" , type=\"cluster_state\"} /1000) by (edge,type)",
     "legendFormat": "{{edge}}/{{type}}"
    }
   ]
  },
  {
   "title": "Time since cluster states were sent to the MPC and Edges clients (seconds)",
   "type": "bargauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max((xcp_central_last_cluster_state_event_timestamp_ms / 1000  unless on(peer_cluster_name) label_replace(increase(xcp_central_current_onboarded_edge[5m]),\"peer_cluster_name\", \"$1\", \"edge\", \"(.*)\") == 0) unless on(cluster_state_event_cluster_name) label_replace(increase(xcp_central_current_onboarded_edge[5m]),\"cluster_state_event_cluster_name\", \"$1\", \"edge\", \"(.*)\") == 0) by (peer_cluster_name, cluster_state_event_cluster_name)",
     "legendFormat": "cluster-state({{cluster_state_event_cluster_name}} )-> client({{peer_cluster_name}})"
    }
   ]
  },
  {
   "title": "Time since config resync  request is received from the edge (seconds)",
   "type": "bargauge",
   "description": "Because regular periodic resync requests would be coming, a high value than the resync period, 60 sec default,  is not normal.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - max(max((increase(xcp_central_current_onboarded_edge_total[2m]) unless increase(xcp_central_current_onboarded_edge_total[2m]) == 0)) by (edge) + on(edge) group_right xcp_central_last_config_propagation_event_timestamp_ms{edge!=\"\", status=\"received\" , type=\"config_resync_request\"} /1000) by (edge,type)",
     "legendFormat": "{{edge}}/{{type}}"
    }
   ]
  },
  {
   "title": "Time since config CRs sent to  the edge (seconds)",
   "type": "bargauge",
   "description": "Sent: Time since configs like workspaces, traffic groups etc were sent to the edge.  In steady state,  a very high value is fine\n",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - max(\n    max((increase(xcp_central_current_onboarded_edge_total[2m]) unless increase(xcp_central_current_onboarded_edge_total[2m]) == 0)) by (edge) + on(edge) group_right xcp_central_last_config_propagation_event_timestamp_ms{edge!=\"\", status=\"sent\"} /1000) by (edge,type)",
     "legendFormat": "{{edge}} "
    }
   ]
  },
  {
   "title": "messages received by central from edges in last 5 min",
   "type": "timeseries",
   "description": "Number of times any message is received by central from edges\n\nMessages received by central from any edge are of three types:\n1. Periodic(per minute by default) config resync request\n2. cluster state\n3. Header message to ack the config received\n\nThis number is combined count of all three in the last 5 min.  ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(xcp_central_config_propagation_event_count_total{status=\"received\",type=\"config_resync_request\"}[5m]) unless on(edge) increase(xcp_central_current_onboarded_edge_total[5m]) == 0",
     "legendFormat": "{{edge}}/{{type}}"
    },
    {
     "expr": "increase(xcp_central_config_propagation_event_count_total{status=\"received\",type=\"cluster_state\"}[5m]) unless on(edge) increase(xcp_central_current_onboarded_edge_total[5m]) == 0",
     "legendFormat": "{{edge}}/{{type}}"
    }
   ]
  },
  {
   "title": "Number of times config CRs sent by central to the edges in last 5m",
   "type": "timeseries",
   "description": "Number of times config CRs like workspaces. traffic groups etc sent by central in last 5m",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(xcp_central_config_propagation_event_count_total{status=\"sent\"}[5m]) unless on(edge) increase(xcp_central_current_onboarded_edge_total[5m]) == 0",
     "legendFormat": "{{edge}} /{{type}}"
    }
   ]
  },
  {
   "title": "Config Propagation Latency by Edge",
   "type": "timeseries",
   "description": "Distribution of time to propagate updates from Central (Management plane) to Edges. If there is no config push in last  one minute, you will see all 0s, which is expected.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(xcp_central_config_propagation_time_ms_bucket{}[1m])) by (le, edge)) unless on(edge) increase(xcp_central_current_onboarded_edge[5m]) == 0",
     "legendFormat": "{{edge}} p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(xcp_central_config_propagation_time_ms_bucket{}[1m])) by (le, edge)) unless on(edge) increase(xcp_central_current_onboarded_edge[5m]) == 0",
     "legendFormat": "{{edge}} p95"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(xcp_central_config_propagation_time_ms_bucket{}[1m])) by (le, edge)) unless on(edge) increase(xcp_central_current_onboarded_edge[5m]) == 0",
     "legendFormat": "{{edge}} p90"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(xcp_central_config_propagation_time_ms_bucket{}[1m])) by (le, edge)) unless on(edge) increase(xcp_central_current_onboarded_edge[5m]) == 0",
     "legendFormat": "{{edge}} p75"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(xcp_central_config_propagation_time_ms_bucket{}[1m])) by (le, edge)) unless on(edge) increase(xcp_central_current_onboarded_edge[5m]) == 0",
     "legendFormat": "{{edge}} p50"
    }
   ]
  },
  {
   "title": "Errors in config push REQUESTS to the edges in last 5 minutes",
   "type": "timeseries",
   "description": "Central enqueues the config push request to the debouncer(an internal component of central) when:\n- It receives event about config resources from k8s apiserver , or\n- Any edge connects first time,  or \n- It is handling a periodic resync request from any of the edges.\n\nIn either case, if central meets an error in the event handling before en-queuing the config push request to the debouncer, this metric gets incremented. \nSo this panel is inversely related to \"config push(to the edges) requests enqueued to debouncer in last 5 min\". ",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "\nincrease(xcp_central_config_update_error_count{}[5m]) OR on() vector(0)",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "config push(to the edges) requests enqueued to debouncer in last 5 min",
   "type": "timeseries",
   "description": "Number of times central enqueued config push(to the connected edges) request to the debouncer in last 5 min. Along with count of the request, reason for the config push request are also shown. \n\nNote: This metric does not indicate the count of actual config push by central. Because of debouncing, actual config push will generally be lesser than this metric. In other words, this metric shows input events for config push. Output (config push on grpc channels to edges) will be lesser because of debouncer\n\nReasons could be:\n1. ADD/DELETE/UPDATE :  These are the events received by the central from the k8s apiserver. Example:\nADD/IngressGateway means count of config push requests enqueued because of new IngressGateway CRs creation at k8s apiserver.\n2. EDGE_RESYNC: This shows the count of config push requests when periodic config resync request from edge triggers config push. This will be non-zero only in rare cases when, for whatever reason, edge reported a stale set of configs and central triggers config push to refresh the configs\n3. EDGE_FIRST_CONNECTION: When any edge connects to central, central syncs config to the edge. In steady state, its count must be 0. If its count is non-zero,  that indicates grpc stream between central and edge is in error and getting reconnected. \n4. CENTRAL_RESYNC: central enqueues a config push request every 5 minute to reconcile configs at edges.  Note that this will result into actual config push only to those edges which are not actively sending their config version periodically. Since 1.4, edges request config resync and therefore central will actually push configs over grpc as a result of these request only if edge is < 1.4. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(xcp_central_config_update_push_count_total{}[5m])",
     "legendFormat": "{{event}}  / {{kind}}"
    }
   ]
  },
  {
   "title": "Pending configurations (orphan configs)",
   "type": "timeseries",
   "description": "Pending configurations are configs for which cluster could not be determined yet because the parent resource is missing.\nThese metrics show which configurations are currently in Pending state, and the missing Parent group configuration due to which this is in Pending state.\n\n\nFor more information on the Pending configurations can be found by using the XCP central debug endpoint - `/debug/cluster_scoped_configs/?pending=true`",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xcp_central_pending_configs_total",
     "legendFormat": "{{kind}} pending on {{reason}}"
    }
   ]
  },
  {
   "title": "Number of connections(cluster state pushing and config pushing)",
   "type": "timeseries",
   "description": "Central has two type of grpc connections:\n1. edge_config_distribution: One grpc connection with each edge for pushing user configs like workspace, trafficgroup etc\n2. cluster_state: One grpc connection with each edge for pushing learned cluster state(service discovery) from all other peer edges. In addition, one more grpc connection with the mpc for pushing all the learned cluster states to the tsb server.\n\ncount of edge_config_distribution will be equal to the number of edges connected to the central\ncount of cluster_state connections will be one more that count of edge_config_distribution connections because of additional mpc connection.\n\nIMPORTANT NOTE: If the cluster is not onboarded(TSB cluster object missing), but the edge is up and connected to central, in that scenario connection counts will include such edges",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xcp_central_current_edge_connections{connection_type=\"edge_config_distribution\"} OR on() vector(0)",
     "legendFormat": "{{connection_type}}"
    },
    {
     "expr": "xcp_central_current_edge_connections{connection_type=\"cluster_state\"} OR on() vector(0)",
     "legendFormat": "{{connection_type}}"
    }
   ]
  },
  {
   "title": "Pending on reference configurations",
   "type": "timeseries",
   "description": "Pending on reference configurations are configs referring to a missing configuration in the TSB hierarchy. The configs are propagated to edges with missing reference resolution metadata. Currently, only Security Settings refer other configurations.\nThese metrics show which configurations are currently in PendingOnRef state, and the missing Parent group configuration due to which this is in PendingOnRef state.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "xcp_central_pending_on_ref_configs_total",
     "legendFormat": "{{kind}} pending on {{reason}}"
    }
   ]
  },
  {
   "title": "validation webhook passed count in last 5 min",
   "type": "timeseries",
   "description": "count of requests that validation webhook passed in last 5 minutes by GVK",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(xcp_central_validation_webhook_passed_count{}[5m]) OR on() vector(0)",
     "legendFormat": "{{group}} / {{resource}}"
    }
   ]
  },
  {
   "title": "New connections per min(cluster state pushing and config pushing)",
   "type": "timeseries",
   "description": "In steady state, edges should be reconnecting continuously to central for cluster state and config streams. Therefore, rate must be 0.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(xcp_central_connection_register_count_total{connection_type=\"cluster_state\"}[1m]) * 60",
     "legendFormat": "{{connection_type}}"
    },
    {
     "expr": "rate(xcp_central_connection_register_count_total{connection_type=\"edge_config_distribution\"}[1m]) * 60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connection Push timeouts[5m]",
   "type": "timeseries",
   "description": "This Panel represents the connection push timeouts in the last 5 minutes in Central grouped by connection types and peer cluster name.\n\nThere are two types of connections: Config Propagation and Cluster State Propagation. If the propagation of data(cluster_state/config_propagation) takes more than the configured timeout duration(2 mins by default), central drops the push. This metric can highlight if pushes of certain connection types are failing in certain edges, helping narrow down the problematic component. The push can get a timeout if the previous send to the edge is taking too long.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "sum by(connection_type, peer_cluster_name) (increase(xcp_central_connection_push_timeout_count[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All goroutines",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{component=\"xcp\",plane=\"management\"}",
     "legendFormat": "All goroutines"
    }
   ]
  },
  {
   "title": "Rate of webhook validation errors",
   "type": "timeseries",
   "description": "Rate of webhook validation errors by GVK",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(xcp_central_validation_webhook_failed_count{}[5m]) OR on() vector(0)",
     "legendFormat": "{{group}} / {{resource}}"
    },
    {
     "expr": "increase(xcp_central_validation_webhook_http_error_count{}[5m]) OR on() vector(0)",
     "legendFormat": "errors due to k8s failures"
    }
   ]
  },
  {
   "title": "Central memory consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{component=\"xcp\",plane=\"management\"}",
     "legendFormat": "Heap InUse"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{component=\"xcp\",plane=\"management\"}",
     "legendFormat": "Stack InUse"
    }
   ]
  },
  {
   "title": "Central specific goroutines",
   "type": "timeseries",
   "description": "This shows the number of active goroutines in XCP Central that are responsible for config pushes to edges.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 73 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(go_goroutines{component=\"xcp\",plane=\"management\"}[1m])",
     "legendFormat": "All goroutines"
    },
    {
     "expr": "increase(xcp_central_go_routine_count_total{}[1m])",
     "legendFormat": "{{go_routine}}"
    }
   ]
  },
  {
   "title": "Edges' memory consumption",
   "type": "timeseries",
   "description": "This shows the current memory usage for all Edges",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{component=\"xcp\",plane=\"control\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "Central CPU consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"central-xcp\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "All edges' CPU consumption",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"edge-xcp\"}[1m])",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  { "title": "XCP Central HA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 } },
  {
   "title": "XCP Central Coordinator running",
   "type": "timeseries",
   "description": "This panel represents if the XCP Central Coordinator is running across the Central instances.",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "avg by(instance) (xcp_central_ha_coordinator_up)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "XCP Central Leader",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (xcp_central_ha_coordinator_acting_as_leader)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "XCP Central Followers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 97 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (xcp_central_ha_coordinator_acting_as_follower)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XCP Central Coordinator Leader election loop[5m]",
   "type": "timeseries",
   "description": "This panel represents how many times the XCP Central Coordinator started the leader election loop in the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_coordinator_leader_election_loops_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XCP Central Primary Relay Streams Total",
   "type": "timeseries",
   "description": "This panel represents how many streams are open in the XCP Central Primary relay server.\n\nAs the leader's switch, the instance name will change.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by(instance) (xcp_central_ha_primary_relay_server_streams_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of currently open relay streams at the H/A Primary (Relay Server)",
   "type": "timeseries",
   "description": "This panel represents the currently open relay stream at the Primary relay server in the XCP Central instances.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
   "targets": [
    {
     "expr": "sum by(instance) (xcp_central_ha_primary_relay_server_streams_open_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Relay streams rejected by primary relay server",
   "type": "timeseries",
   "description": "Total number of relay streams rejected by the H/A Primary (Relay Server) because the current XCP Central instance is not the H/A Leader",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_primary_relay_server_streams_rejected_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of relay streams discontinued by primary relay server",
   "type": "timeseries",
   "description": "Total number of relay streams closed forcibly by the H/A Primary (Relay Server) because current XCP Central instance stopped being the H/A Leader",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "targets": [
    {
     "expr": "xcp_central_ha_primary_relay_server_streams_discontinued_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total cluster states sent by primary relay server(Leader->Follower)[5m]",
   "type": "timeseries",
   "description": "Total number of Cluster state updates pushed by the H/A Primary (Relay Server) to H/A Secondary(s) (Relay Client(s))",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_primary_relay_server_cluster_states_sent_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster States received by primary relay server(Follower->Leader)[5m]",
   "type": "timeseries",
   "description": "Total number of Cluster state updates received by the H/A Primary (Relay Server) from H/A Secondary(s) (Relay Client(s))",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_primary_relay_server_cluster_states_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state is sent by primary to Secondary for Different CPs[5m]",
   "type": "timeseries",
   "description": "Total number of times a Cluster state has been pushed by the H/A Primary (Relay Server) to H/A Secondary(s) (Relay Client(s))",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(xcp_central_ha_primary_relay_server_cluster_state_sent_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster states received by primary from secondaries for different CP[5m]",
   "type": "timeseries",
   "description": "Total number of times a Cluster state has been received by the H/A Primary (Relay Server) from H/A Secondary(s) (Relay Client(s))",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(xcp_central_ha_primary_relay_server_cluster_state_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Secondary relay client running",
   "type": "gauge",
   "description": "Flag indicating whether H/A Secondary (Relay Client) is running",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(instance) (xcp_central_ha_secondary_relay_client_up)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of Second relay client stream",
   "type": "timeseries",
   "description": "Total number of relay streams opened by the H/A Secondary (Relay Client)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 141 },
   "targets": [
    {
     "expr": "avg by(instance) (xcp_central_ha_secondary_relay_client_streams_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of open relay stream by secondary relay client",
   "type": "timeseries",
   "description": "Number of currently open relay streams by the H/A Secondary (Relay Client)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 141 },
   "targets": [
    {
     "expr": "sum by(instance) (xcp_central_ha_secondary_relay_client_streams_open_count_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state updates recvd by secondary relay client from Primary[5m]",
   "type": "timeseries",
   "description": "Total number of Cluster state updates received by the H/A Secondary (Relay Client) from the H/A Primary (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_secondary_relay_client_cluster_states_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster states sent by secondary relay client to primary[5m]",
   "type": "timeseries",
   "description": "Total number of Cluster state updates pushed by the H/A Secondary (Relay Client) to the H/A Primary (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 149 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_secondary_relay_client_cluster_states_sent_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state updates recvd by secondary client from primary for different CPs[5m]",
   "type": "timeseries",
   "description": "Total number of times a Cluster state has been received by the H/A Secondary (Relay Client) from the H/A Primary (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 157 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(xcp_central_ha_secondary_relay_client_cluster_state_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state updates sent by secondary relay to primary relay for different CPs[5m]",
   "type": "timeseries",
   "description": "Total number of times a Cluster state has been pushed by the H/A Secondary (Relay Client) to the H/A Primary (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 157 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(xcp_central_ha_secondary_relay_client_cluster_state_sent_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "XCP Central Cross Partition enabled",
   "type": "gauge",
   "description": "Flag indicating whether support for Cross-Partition H/A is enabled",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 165 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(xcp_central_ha_cross_partition_enabled)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of relay streams by H/A Cross-Paritition Requestor",
   "type": "timeseries",
   "description": "Total number of relay streams opened by the H/A Cross-Partition Requestor (Relay Client)",
   "gridPos": { "h": 6, "w": 9, "x": 6, "y": 165 },
   "targets": [
    {
     "expr": "avg by(instance) (xcp_central_ha_cross_partition_requestor_relay_client_streams_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of open streams by Cross-partition requestor",
   "type": "timeseries",
   "description": "Number of currently open relay streams by the H/A Cross-Partition Requestor (Relay Client)",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 165 },
   "targets": [
    {
     "expr": "sum by(instance) (xcp_central_ha_cross_partition_requestor_relay_client_streams_open_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state updates recvd by H/A Cross-partition requestor[5m]",
   "type": "timeseries",
   "description": "Total number of Cluster state updates received by the H/A Cross-Partition Requestor (Relay Client) from the H/A Cross-Partition Responder (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 171 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_cross_partition_requestor_relay_client_cluster_states_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state updates recvd by H/A Cross partition requestor for different CPs[5m]",
   "type": "timeseries",
   "description": "Total number of times a Cluster state has been received by the H/A Cross-Partition Requestor (Relay Client) from the H/A Cross-Partition Responder (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 171 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(xcp_central_ha_cross_partition_requestor_relay_client_cluster_state_received_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of relay streams by H/A Cross-Paritition Responder",
   "type": "timeseries",
   "description": "Total number of relay streams opened by the H/A Cross-Partition Responder (Relay Client)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 179 },
   "targets": [
    {
     "expr": "avg by(instance) (xcp_central_ha_cross_partition_responder_relay_server_streams_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of open streams by Cross-partition responder",
   "type": "timeseries",
   "description": "Number of currently open relay streams at the H/A Cross-Partition Responder (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 179 },
   "targets": [
    {
     "expr": "sum by(instance) (xcp_central_ha_cross_partition_requestor_relay_client_streams_open_count)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state updates sent by H/A Cross-partition responder[5m]",
   "type": "timeseries",
   "description": "Total number of Cluster state updates sent by the H/A Cross-Partition Responder (Relay Client) to the H/A Cross-Partition Requestor (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "targets": [
    {
     "expr": "sum by(instance) (increase(xcp_central_ha_cross_partition_responder_relay_server_cluster_states_sent_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of cluster state updates sent by H/A Cross partition responder for different CPs[5m]",
   "type": "timeseries",
   "description": "Total number of times a Cluster state has been sent by the H/A Cross-Partition Responder (Relay Client) to the H/A Cross-Partition Requestor (Relay Server)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "targets": [
    {
     "expr": "sum by(cluster) (increase(xcp_central_ha_cross_partition_responder_relay_server_cluster_state_sent_total[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}