{
 "title": "XCP Edge status",
 "tags": [
  "tsb",
  "xcp",
  "edge"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "cluster", "label": "cluster", "query": { "query": "label_values(cluster_name)" } }
  ]
 },
 "panels": [
  {
   "title": "XCP Edge",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdhms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{cluster_name=\"$cluster\",component=\"xcp\"}"
    }
   ]
  },
  {
   "title": "XCP Edge Version",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(xcp_edge_version{cluster_name=\"$cluster\"}, \"xcp_version\", \"$1\", \"version\", \"(.*)\")"
    },
    {
     "expr": "label_replace(xcp_edge_istio_versions{cluster_name=\"$cluster\"}, \"istio_versions\", \"$1\", \"version\", \"(.*)\")"
    }
   ]
  },
  {
   "title": "Number of gatewayHost exposed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xcp_edge_gateway_hosts_count{cluster_name=\"$cluster\"}",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Active connections to central",
   "type": "stat",
   "description": "Current peer connections this edge holds against remote edges.",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "xcp_edge_stream_connect_count_total{statusLabel=\"ok\", cluster_name=\"$cluster\"} - ignoring(statusLabel) xcp_edge_stream_connect_count_total{statusLabel=\"close\", cluster_name=\"$cluster\"} OR on() xcp_edge_stream_connect_count_total{statusLabel=\"ok\", cluster_name=\"$cluster\"} ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  { "title": "SENT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Time since any message sent to central on config stream (seconds)",
   "type": "bargauge",
   "description": "Time since any of the following messages is sent by edge to central:\n1. Periodic(per minute) config resync request\n2. Ack of last config received \n3. Cluster state\nBecause regular periodic resync requests would be going out periodically, a high value than the resync period, 60 sec default,  is not normal.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - xcp_edge_last_push_to_central_timestamp_ms{cluster_name=\"$cluster\"} / 1000",
     "legendFormat": "cluster-state:{{trigger_reason}}"
    },
    {
     "expr": "time() - xcp_edge_last_config_resync_to_central_timestamp_ms{cluster_name=\"$cluster\"} / 1000",
     "legendFormat": "config resync request"
    }
   ]
  },
  {
   "title": "cluster-state build time percentiles(in secs)",
   "type": "bargauge",
   "description": "Time (in ms) taken to build the local cluster state. This build time is subset of cluster-update-propagation time",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(xcp_edge_cluster_state_build_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(xcp_edge_cluster_state_build_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95,sum(xcp_edge_cluster_state_build_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(xcp_edge_cluster_state_build_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1,sum(xcp_edge_cluster_state_build_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Number of times cluster states sent to central",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_count{cluster_name=\"$cluster\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "cluster-state propagation delay percentiles(in secs)",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95,sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1,sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "propagated to central  in 0-1.5 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"1.5\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "Number of times config status sent by edge to central in last 5 min",
   "type": "graph",
   "description": "Number of times config statuses are sent by edge to central, with respective objects' Kind.\n\nMessages received by central from any edge are of three types:\n1. Periodic(per minute by default) config resync request\n2. cluster state\n3. Header message to ack the config received\n\nThis number is combined count of all three in the last 5 min.  ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(xcp_edge_config_status_updates_sent_gvk_total{cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{kind}}"
    }
   ]
  },
  {
   "title": "propagated to central  in 1.5-2.5 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"2.5\"} - ignoring(le,cluster_name) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"1.5\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "propagated to central  in 2.5-4 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 29 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"4\"} - ignoring(le,cluster_name) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"2.5\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "Length of cluster state event queue",
   "type": "timeseries",
   "description": "Length of the cluster state events queue at the current moment. This metric is useful to track the cluster state events currently in the queue and ready to be dequeued and sent to central. A high value of this metric means that events are getting enqueued but dequeuing is blocked because of some bottleneck at sending to the central part.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "xcp_edge_current_state_state_events_queue_len{cluster_name=\"$cluster\"}",
     "legendFormat": "{{cluster_name}}"
    }
   ]
  },
  {
   "title": "propagated to central  in 4-7 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 32 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"7\"} - ignoring(le) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"4\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "propagated to central  in 11-15 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"15\"} - ignoring(le) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"11\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "propagated to central  in 7-11 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 38 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"11\"} - ignoring(le) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"7\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "propagated to central  in 15-20 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 41 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"20\"} - ignoring(le) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"15\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "propagated to central  in 20-30 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"30\"} - ignoring(le) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"20\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "propagated to central  in 30-40 secs",
   "type": "bargauge",
   "description": "Time (in secs) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 47 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"40\"} - ignoring(le) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"30\"}) by (trigger_reason)"
    }
   ]
  },
  {
   "title": "propagated to central  in more than 40 secs",
   "type": "bargauge",
   "description": "Time (in ms) taken to propagate a change in the local cluster state to remote central",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(xcp_edge_local_cluster_update_propagation_time_secs_count{cluster_name=\"$cluster\"} - ignoring(le) xcp_edge_local_cluster_update_propagation_time_secs_bucket{cluster_name=\"$cluster\", le=\"40\"}) by (trigger_reason)"
    }
   ]
  },
  { "title": "Received", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Number of times cluster states received by edge from central in last 1 min",
   "type": "graph",
   "description": "Number of times cluster states are received by edge from central in the last 1 min.  ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(xcp_edge_cluster_state_received_from_central_count_total{cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "cluster state received for {{peer}}"
    }
   ]
  },
  {
   "title": "config translation duration percentiles(in ms)",
   "type": "bargauge",
   "description": "Total time taken in completing Istio translation for all the app namespaces",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(xcp_edge_total_translation_time_in_ms_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.9,sum(xcp_edge_total_translation_time_in_ms_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95,sum(xcp_edge_total_translation_time_in_ms_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99,sum(xcp_edge_total_translation_time_in_ms_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(1,sum(xcp_edge_total_translation_time_in_ms_bucket{cluster_name=\"$cluster\"}) by (le))",
     "legendFormat": "p100"
    }
   ]
  },
  {
   "title": "Number of times config CRs received by edge from central in last 5 min",
   "type": "graph",
   "description": "Number of times cluster states are received by edge from central",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(xcp_edge_config_updates_received_count_total{cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "from {{peer}}"
    }
   ]
  },
  {
   "title": "Translation count per min",
   "type": "bargauge",
   "description": "Number of Istio config translations in Edge per namespace per min",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "increase(xcp_edge_istio_translations_count_total{cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Resource activity",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of configs created/updated by edge at k8s apiserver  every 5 minutes",
   "type": "graph",
   "description": "Shows the activity of Edge creating objects in K8s API, grouped by object kind.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(xcp_edge_cr_added_total{cluster_name=\"$cluster\"}[5m]) OR increase(xcp_edge_cr_updated_total{cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ group }}/{{ kind }} "
    }
   ]
  },
  {
   "title": "Number of configs deleted by edge from k8s apiserver  every 5 minutes",
   "type": "graph",
   "description": "Shows the activity of Edge deleting objects in K8s API, grouped by object kind.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(xcp_edge_cr_deleted_total{cluster_name=\"$cluster\"}[5m])",
     "legendFormat": "{{ group }}/{{ kind }}"
    }
   ]
  },
  {
   "title": "k8s config apply duration P50 percentiles for each namespace (in ms)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5,sum(xcp_edge_k8s_configs_apply_time_secs_bucket{cluster_name=\"$cluster\"}) by (le,namespace))"
    }
   ]
  },
  {
   "title": "k8s config apply duration P90 percentiles for each namespace (in ms)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9,sum(xcp_edge_k8s_configs_apply_time_secs_bucket{cluster_name=\"$cluster\"}) by (le,namespace))"
    }
   ]
  },
  {
   "title": "k8s config apply duration P99 percentiles for each namespace (in ms)",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,sum(xcp_edge_k8s_configs_apply_time_secs_bucket{cluster_name=\"$cluster\"}) by (le,namespace))"
    }
   ]
  },
  {
   "title": "Internals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 85 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All goroutines",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{cluster_name=\"$cluster\", component=\"xcp\"}",
     "legendFormat": "All goroutines"
    }
   ]
  },
  {
   "title": "Edge specific gorountines",
   "type": "graph",
   "description": "This shows the number of active goroutines in XCP Edge that are responsible for config translation.",
   "gridPos": { "h": 5, "w": 19, "x": 5, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(xcp_edge_go_routine_count_total{cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "{{go_routine}}"
    }
   ]
  },
  {
   "title": "Edge CPU consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"edge-xcp\",cluster_name=\"$cluster\"}[1m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Edge memory consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 15, "x": 9, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{component=\"xcp\",cluster_name=\"$cluster\"}",
     "legendFormat": "Heap InUse"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{component=\"xcp\",cluster_name=\"$cluster\"}",
     "legendFormat": "Stack InUse"
    }
   ]
  },
  { "title": "XCP Edge Kubernetes Registry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 }, "repeat": "cluster" },
  {
   "title": "Custom Resource events[5m]",
   "type": "timeseries",
   "description": "This panel represents the increase in custom resource events received by the edge registry controller in the last 5 minutes.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 100 },
   "targets": [
    {
     "expr": "sum by(kind) (increase(xcp_edge_registry_kubernetes_custom_resource_events_total{cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EDS Update events[5m]",
   "type": "timeseries",
   "description": "This Panel represents the increase in EDS update events received by the Edge registry controller in the last 5 minutes.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 100 },
   "targets": [
    {
     "expr": "sum(rate(xcp_edge_registry_kubernetes_eds_update_events_received_total{cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Increase in EDS Update events"
    }
   ]
  },
  {
   "title": "Namespace Events[5m]",
   "type": "timeseries",
   "description": "This panel represents the increase in namespace events received by the Edge in the last 5-minute interval. Edge responds to the namespace events through its namespace controller.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 100 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(xcp_edge_registry_kubernetes_namespace_events_received_total{cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Node Events received[5m]",
   "type": "timeseries",
   "description": "This panel represents the increase in node events received by the Edge Kubernetes registry controller in the last 5 minutes.\n\nThere are two different sources for node events. Edge responds differently for different node event sources:\n- Node Controller: Used for Gateway Hold webhook\n- XDS Updater Config Update: Used to update node port service addresses",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 108 },
   "targets": [
    {
     "expr": "sum by(node_event_source) (increase(xcp_edge_registry_kubernetes_node_events_received_total{cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Node events recvd by {{ node_event_source }}"
    }
   ]
  },
  {
   "title": "SvcUpdate events[5m]",
   "type": "timeseries",
   "description": "This panel represents the Svc Update events received by the edge Kubernetes registry controller in 5-minute intervals. ",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 108 },
   "targets": [
    {
     "expr": "sum(increase(xcp_edge_registry_kubernetes_svc_update_events_received_total{cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "Service update events"
    }
   ]
  },
  {
   "title": "Service Entry events received[5m]",
   "type": "timeseries",
   "description": "This Panel represents the increase in Service entry events received by the Edge Kubernetes registry controller in the last 5 minutes.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 108 },
   "targets": [
    {
     "expr": "sum by(event_type) (increase(xcp_edge_registry_kubernetes_service_entry_events_received_total{cluster_name=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}