---
apiVersion: tsb.tetrate.io/v2
kind: Tenant
metadata:
  name: dev
  annotations:
    tsb.tetrate.io/organization: tetrate
spec:
  description: dev
---
apiVersion: tsb.tetrate.io/v2
kind: Workspace
metadata:
  name: gitops-bookinfo-ws
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
spec:
  namespaceSelector:
    names:
      - "*/gitops-bookinfo"
      - "*/gitops-tier1"
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: Group
metadata:
  name: gitops-bookinfo-gg
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: gitops-bookinfo-ws
spec:
  namespaceSelector:
    names:
      - "*/gitops-bookinfo"
      - "*/gitops-tier1"
  configMode: BRIDGED
---
apiVersion: traffic.tsb.tetrate.io/v2
kind: Group
metadata:
  name: gitops-bookinfo-tg
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: gitops-bookinfo-ws
spec:
  namespaceSelector:
    names:
      - "*/gitops-bookinfo"
      - "*/gitops-tier1"
  configMode: BRIDGED
---
apiVersion: security.tsb.tetrate.io/v2
kind: Group
metadata:
  name: gitops-bookinfo-sg
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: gitops-bookinfo-ws
spec:
  namespaceSelector:
    names:
      - "*/gitops-bookinfo"
      - "*/gitops-tier1"
  configMode: BRIDGED
---
apiVersion: install.tetrate.io/v1alpha1
kind: IngressGateway
metadata:
  name: gitops-bookinfo-gw
  namespace: gitops-bookinfo
spec:
  kubeSpec:
    service:
      type: LoadBalancer
---
apiVersion: gateway.tsb.tetrate.io/v2
kind: IngressGateway
metadata:
  name: gitops-bookinfo-igw
  annotations:
    tsb.tetrate.io/organization: tetrate
    tsb.tetrate.io/tenant: dev
    tsb.tetrate.io/workspace: gitops-bookinfo-ws
    tsb.tetrate.io/gatewayGroup: gitops-bookinfo-gg
spec:
  workloadSelector:
    namespace: gitops-bookinfo
    labels:
      app: gitops-bookinfo-gw
  http:
    - name: productpage
      port: 80
      hostname: "gitops-bookinfo.tetrate.io"
      routing:
        rules:
          - route:
              host: "gitops-bookinfo/productpage.gitops-bookinfo.svc.cluster.local"
              port: 9080
    - name: details
      port: 80
      hostname: "gitops-details.tetrate.io"
      routing:
        rules:
          - route:
              host: "gitops-bookinfo/details.gitops-bookinfo.svc.cluster.local"
              port: 9080
