---
apiVersion: v1
kind: List
items:
  - apiVersion: tsb.tetrate.io/v2
    kind: Tenant
    metadata:
      name: dev
      annotations:
        tsb.tetrate.io/organization: tetrate
      labels:
        domain: dev
    spec:
      description: dev
      displayName: dev
      deletionProtectionEnabled: true
  - apiVersion: tsb.tetrate.io/v2
    kind: Workspace
    metadata:
      name: bookinfo-ws
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        owner: bookinfo-ws-team
      labels:
        app: bookinfo
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
          - "*/tier1"
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-gg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
          - "*/tier1"
      configMode: BRIDGED
  - apiVersion: traffic.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-tg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
          - "*/tier1"
      configMode: BRIDGED
  - apiVersion: security.tsb.tetrate.io/v2
    kind: Group
    metadata:
      name: bookinfo-sg
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
    spec:
      namespaceSelector:
        names:
          - "*/bookinfo"
          - "*/tier1"
      configMode: BRIDGED
  - apiVersion: install.tetrate.io/v1alpha1
    kind: IngressGateway
    metadata:
      name: bookinfo-gw
      namespace: bookinfo
    spec:
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: bookinfo-gw
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      workloadSelector:
        namespace: bookinfo
        labels:
          app: bookinfo-gw
      http:
        - name: productpage
          port: 80
          hostname: "bookinfo.tetrate.io"
          routing:
            rules:
              - route:
                  serviceDestination:
                    host: "bookinfo/productpage.bookinfo.svc.cluster.local"
                    port: 9080
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      labels:
        app: trafficgenerator
      name: trafficgenerator
      namespace: bookinfo
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      selector:
        matchLabels:
          app: trafficgenerator
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: trafficgenerator
        spec:
          containers:
            - args:
                - /bin/sh
                - -c
                - 'while true; do curl -i -H"Host: bookinfo.tetrate.io" bookinfo-gw.bookinfo/productpage; do curl -i -H"Host: bookinfo.tetrate.io" tier1-gw.tier1/productpage; done'
              image: appropriate/curl
              imagePullPolicy: Always
              name: trafficgenerator
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
  - apiVersion: install.tetrate.io/v1alpha1
    kind: Tier1Gateway
    metadata:
      name: tier1-gw
      namespace: tier1
    spec:
      kubeSpec:
        service:
          type: LoadBalancer
  - apiVersion: gateway.tsb.tetrate.io/v2
    kind: Gateway
    metadata:
      name: tier1-bookinfo-gw
      annotations:
        tsb.tetrate.io/organization: tetrate
        tsb.tetrate.io/tenant: dev
        tsb.tetrate.io/workspace: bookinfo-ws
        tsb.tetrate.io/gatewayGroup: bookinfo-gg
    spec:
      workloadSelector:
        namespace: tier1
        labels:
          app: tier1-gw
      http:
        - name: productpage
          port: 80
          hostname: "bookinfo.tetrate.io"
          routing:
            rules:
              - route:
                  clusterDestination:
                    clusters: []
---
